use_frameworks!

pod 'secp256k1.swift'

target 'JWTsSwift_Tests' do
  pod 'JWTsSwift', :path => '../'
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
          target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
          end
        end
   end
end
